export const GET_CAMPAIGN_LIST_PENDING = "GET_CAMPAIGN_LIST_PENDING";
export const GET_CAMPAIGN_LIST_SUCCESS = "GET_CAMPAIGN_LIST_SUCCESS";
export const GET_CAMPAIGN_LIST_ERROR = "GET_CAMPAIGN_LIST_ERROR";
export const GET_LEADS_LIST_PENDING = "GET_LEADS_LIST_PENDING";
export const GET_LEADS_LIST_SUCCESS = "GET_LEADS_LIST_SUCCESS";
export const GET_LEADS_LIST_ERROR = "GET_LEADS_LIST_ERROR";
export const GET_LEADS_UPDATESTATUS_PENDING = "GET_LEADS_UPDATESTATUS_PENDING";
export const GET_LEADS_UPDATESTATUS_SUCCESS = "GET_LEADS_UPDATESTATUS_SUCCESS";
export const GET_LEADS_UPDATESTATUS_ERROR = "GET_LEADS_UPDATESTATUS_ERROR";
export const GET_APPROVE_COUNT = "GET_APPROVE_COUNT"
export const GET_REJECT_COUNT = "GET_REJECT_COUNT"
export const GET_UNDERREVIEW_COUNT = "GET_UNDERREVIEW_COUNT"
export const GET_ARCHIEVE_COUNT = "GET_ARCHIEVE_COUNT"
export const GET_ALL_COUNT = "GET_ALL_COUNT"
export const GET_POPUP_DISABLE = "GET_POPUP_DISABLE";
export const GET_POPUP_ENABLE = "GET_POPUP_ENABLE";


export const DATE_MODAL_OPEN = " DATE_MODAL_OPEN";
export const DATE_MODAL_CLOSE = " DATE_MODAL_CLOSE";


export const POST_CAMPAIGN_DATA_PENDING = "POST_CAMPAIGN_DATA_PENDING";
export const POST_CAMPAIGN_DATA_SUCCESS = "POST_CAMPAIGN_DATA_SUCCESS";
export const POST_CAMPAIGN_DATA_ERROR = "POST_CAMPAIGN_DATA_ERROR";

export const GET_A_CAMPAIGN_PENDING = "GET_A_CAMPAIGN_PENDING";
export const GET_A_CAMPAIGN_SUCCESS = "GET_A_CAMPAIGN_SUCCESS";
export const GET_A_CAMPAIGN_ERROR = "GET_A_CAMPAIGN_ERROR";

export const DELETE_CAMPAIGN_DATA_SUCCESS = "DELETE_CAMPAIGN_DATA_SUCCESS";
export const DELETE_CAMPAIGN_DATA_ERROR = "DELETE_CAMPAIGN_DATA_ERROR";

export const UPDATE_CAMPAIGN_DATA_SUCCESS = "UPDATE_CAMPAIGN_DATA_SUCCESS";
export const UPDATE_CAMPAIGN_DATA_ERROR = "UPDATE_CAMPAIGN_DATA_ERROR";

export const SHOW_MODAL = "SHOW_MODAL";
export const HANDLE_OPEN = "HANDLE_OPEN";
export const HANDLE_CLOSE = "HANDLE_CLOSE";

export const CAMPAIGN_ID = "CAMPAIGN_ID";

export const UPDATE_STATUS_DATA_ACTIVE = "UPDATE_STATUS_DATA_ACTIVE";
export const UPDATE_STATUS_DATA_IN_ACTIVE = "UPDATE_STATUS_DATA_IN_ACTIVE";

export const SEARCH_INPUT_VALUE = "SEARCH_INPUT_VALUE";

export const FILTER_LEADS_CAMPAIGNNAME = "FILTER_LEADS_CAMPAIGNNAME"
export const FILTER_LEADS_OWNERNAME = "FILTER_LEADS_OWNERNAME"
export const FILTER_LEADS_SEARCH = "FILTER_LEADS_SEARCH"
export const FILTER_LEADS_DATE = "FILTER_LEADS_DATE"
export const FILTER_LEADS_CLEAR = "FILTER_LEADS_CLEAR"

export const GET_TOTAL_COUNT = "GET_TOTAL_COUNT"
export const GET_LEADS_PER_PAGE = "GET_LEADS_PER_PAGE"
export const GET_ACTIVE_COUNT = "GET_ACTIVE_COUNT"


