export const GET_CAMPAIGN_LIST_PENDING = "GET_CAMPAIGN_LIST_PENDING";
export const GET_CAMPAIGN_LIST_SUCCESS = "GET_CAMPAIGN_LIST_SUCCESS";
export const GET_CAMPAIGN_LIST_ERROR = "GET_CAMPAIGN_LIST_ERROR";
export const GET_LEADS_LIST_PENDING = "GET_LEADS_LIST_PENDING";
export const GET_LEADS_LIST_SUCCESS = "GET_LEADS_LIST_SUCCESS";
export const GET_LEADS_LIST_ERROR = "GET_LEADS_LIST_ERROR";
export const GET_LEADS_UPDATESTATUS_PENDING = "GET_LEADS_UPDATESTATUS_PENDING";
export const GET_LEADS_UPDATESTATUS_SUCCESS = "GET_LEADS_UPDATESTATUS_SUCCESS";
export const GET_LEADS_UPDATESTATUS_ERROR = "GET_LEADS_UPDATESTATUS_ERROR";
export const GET_APPROVE_COUNT = "GET_APPROVE_COUNT"
export const GET_REJECT_COUNT = "GET_REJECT_COUNT"
export const GET_UNDERREVIEW_COUNT = "GET_UNDERREVIEW_COUNT"
export const GET_POPUP_DISABLE = "GET_POPUP_DISABLE";
export const GET_POPUP_ENABLE = "GET_POPUP_ENABLE";


export const POST_CAMPAIGN_DATA_PENDING = "POST_CAMPAIGN_DATA_PENDING";
export const POST_CAMPAIGN_DATA_SUCCESS = "POST_CAMPAIGN_DATA_SUCCESS";
export const POST_CAMPAIGN_DATA_ERROR = "POST_CAMPAIGN_DATA_ERROR";

export const GET_A_CAMPAIGN_PENDING = "GET_A_CAMPAIGN_PENDING";
export const GET_A_CAMPAIGN_SUCCESS = "GET_A_CAMPAIGN_SUCCESS";
export const GET_A_CAMPAIGN_ERROR = "GET_A_CAMPAIGN_ERROR";

export const DELETE_CAMPAIGN_DATA_SUCCESS = "DELETE_CAMPAIGN_DATA_SUCCESS";
export const DELETE_CAMPAIGN_DATA_ERROR = "DELETE_CAMPAIGN_DATA_ERROR";

export const UPDATE_CAMPAIGN_DATA_SUCCESS = "UPDATE_CAMPAIGN_DATA_SUCCESS";
export const UPDATE_CAMPAIGN_DATA_ERROR = "UPDATE_CAMPAIGN_DATA_ERROR";

export const SHOW_MODAL = "SHOW_MODAL";
export const HANDLE_OPEN = "HANDLE_OPEN";
export const HANDLE_CLOSE = "HANDLE_CLOSE";

export const CAMPAIGN_ID = "CAMPAIGN_ID";

export const UPDATE_STATUS_DATA_ACTIVE = "UPDATE_STATUS_DATA_ACTIVE";
export const UPDATE_STATUS_DATA_IN_ACTIVE = "UPDATE_STATUS_DATA_IN_ACTIVE";

export const SEARCH_INPUT_VALUE = "SEARCH_INPUT_VALUE";