export const GET_CAMPAIGN_LIST_PENDING = "GET_CAMPAIGN_LIST_PENDING";
export const GET_CAMPAIGN_LIST_SUCCESS = "GET_CAMPAIGN_LIST_SUCCESS";
export const GET_CAMPAIGN_LIST_ERROR = "GET_CAMPAIGN_LIST_ERROR";

export const GET_LEADS_LIST_PENDING = "GET_LEADS_LIST_PENDING";
export const GET_LEADS_LIST_SUCCESS = "GET_LEADS_LIST_SUCCESS";
export const GET_LEADS_LIST_ERROR = "GET_LEADS_LIST_ERROR";

export const GET_LEADS_LIST_FULL_DESCRIPTION_PENDING =
  "GET_LEADS_LIST_FULL_DESCRIPTION_PENDING";
export const GET_LEADS_LIST_FULL_DESCRIPTION_SUCCESS =
  "GET_LEADS_LIST_FULL_DESCRIPTION_SUCCESS";
export const GET_LEADS_LIST_FULL_DESCRIPTION_ERROR =
  "GET_LEADS_LIST_FULL_DESCRIPTION_ERROR";

export const GET_LEADS_UPDATESTATUS_PENDING = "GET_LEADS_UPDATESTATUS_PENDING";
export const GET_LEADS_UPDATESTATUS_SUCCESS = "GET_LEADS_UPDATESTATUS_SUCCESS";
export const GET_LEADS_UPDATESTATUS_ERROR = "GET_LEADS_UPDATESTATUS_ERROR";

export const GET_APPROVE_COUNT = "GET_APPROVE_COUNT";
export const GET_REJECT_COUNT = "GET_REJECT_COUNT";
export const GET_UNDERREVIEW_COUNT = "GET_UNDERREVIEW_COUNT";
export const GET_ARCHIEVE_COUNT = "GET_ARCHIEVE_COUNT";
export const GET_ALL_COUNT = "GET_ALL_COUNT";

export const GET_LEAD_DATA = "GET_LEAD_DATA";

export const DATE_MODAL_OPEN = " DATE_MODAL_OPEN";
export const DATE_MODAL_CLOSE = " DATE_MODAL_CLOSE";

export const POST_CAMPAIGN_DATA_PENDING = "POST_CAMPAIGN_DATA_PENDING";
export const POST_CAMPAIGN_DATA_SUCCESS = "POST_CAMPAIGN_DATA_SUCCESS";
export const POST_CAMPAIGN_DATA_ERROR = "POST_CAMPAIGN_DATA_ERROR";

export const GET_A_CAMPAIGN_PENDING = "GET_A_CAMPAIGN_PENDING";
export const GET_A_CAMPAIGN_SUCCESS = "GET_A_CAMPAIGN_SUCCESS";
export const GET_A_CAMPAIGN_ERROR = "GET_A_CAMPAIGN_ERROR";

export const DELETE_CAMPAIGN_DATA_SUCCESS = "DELETE_CAMPAIGN_DATA_SUCCESS";
export const DELETE_CAMPAIGN_DATA_ERROR = "DELETE_CAMPAIGN_DATA_ERROR";

export const UPDATE_CAMPAIGN_DATA_PENDING = "UPDATE_CAMPAIGN_DATA_PENDING";
export const UPDATE_CAMPAIGN_DATA_SUCCESS = "UPDATE_CAMPAIGN_DATA_SUCCESS";
export const UPDATE_CAMPAIGN_DATA_ERROR = "UPDATE_CAMPAIGN_DATA_ERROR";

export const SHOW_MODAL = "SHOW_MODAL";
export const HANDLE_OPEN = "HANDLE_OPEN";
export const HANDLE_CLOSE = "HANDLE_CLOSE";

export const CAMPAIGN_ID = "CAMPAIGN_ID";

export const UPDATE_STATUS_DATA_ACTIVE = "UPDATE_STATUS_DATA_ACTIVE";
export const UPDATE_STATUS_DATA_IN_ACTIVE = "UPDATE_STATUS_DATA_IN_ACTIVE";

export const SEARCH_INPUT_VALUE = "SEARCH_INPUT_VALUE";
export const SEARCHED_CAMPAIGNS = "SEARCHED_CAMPAIGNS";

export const FILTER_LEADS_CAMPAIGNNAME = "FILTER_LEADS_CAMPAIGNNAME";
export const FILTER_LEADS_OWNERNAME = "FILTER_LEADS_OWNERNAME";
export const FILTER_LEADS_SEARCH = "FILTER_LEADS_SEARCH";
export const FILTER_LEADS_DATE = "FILTER_LEADS_DATE";
export const FILTER_LEADS_CLEAR = "FILTER_LEADS_CLEAR";
export const SET_DATEPICKER_STATE = "SET_DATEPICKER_STATE";
export const FILTER_LEADS_COUNTRIES = "FILTER_LEADS_COUNTRIES";

export const GET_TOTAL_COUNT = "GET_TOTAL_COUNT";
export const GET_DATA_PER_PAGE = " GET_DATA_PER_PAGE";
export const GET_ACTIVE_COUNT = "GET_ACTIVE_COUNT";

export const CARDS_DISPLAYED = "CARDS_DISPLAYED";

export const OPEN_ALERT = "OPEN_ALERT";
export const CLOSE_ALERT = "CLOSE_ALERT";

export const LEADS_DROPDOWN_FILTER = "LEADS_DROPDOWN_FILTER";

export const OPEN_LOADER = "OPEN_LOADER";
export const CLOSE_LOADER = "CLOSE_LOADER";

export const GET_USERS_PENDING = "GET_USERS_PENDING";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const ASSIGN_LEAD_PENDING = "ASSIGN_LEAD_PENDING";
export const ASSIGN_LEAD_SUCCESS = "ASSIGN_LEAD_SUCCESS";
export const ASSIGN_LEAD_ERROR = "ASSIGN_LEAD_ERROR";

export const ASSIGN_CAMPAIGN_PENDING = "ASSIGN_CAMPAIGN_PENDING";
export const ASSIGN_CAMPAIGN_SUCCESS = "ASSIGN_CAMPAIGN_SUCCESS";
export const ASSIGN_CAMPAIGN_ERROR = "ASSIGN_CAMPAIGN_ERROR";

export const ADD_NOTES_PENDING = "ADD_NOTES_PENDING";
export const ADD_NOTES_SUCCESS = "ADD_NOTES_SUCCESS";
export const ADD_NOTES_ERROR = "ADD_NOTES_ERROR";

export const UPDATE_LEAD_VIEW_PENDING = "UPDATE_LEAD_VIEW_PENDING";
export const UPDATE_LEAD_VIEW_SUCCESS = "UPDATE_LEAD_VIEW_SUCCESS";
export const UPDATE_LEAD_VIEW_ERROR = "UPDATE_LEAD_VIEW_ERROR";

export const CAMPAIGN_OWNER_FILTER_VALUE = "CAMPAIGN_OWNER_FILTER_VALUE";
export const CAMPAIGN_COUNTRY_FILTER_VALUE = "CAMPAIGN_COUNTRY_FILTER_VALUE";
export const CAMPAIGN_FILTER_CLEAR = "CAMPAIGN_FILTER_CLEAR";
